/* ==================================================================
 *  Map Generators — SillyTavern extension
 *
 *  Embeds Watabou's procedural map generators, keeps a per-chat
 *  library of maps, and feeds a text description of each map to the
 *  AI (via a chat-bound lorebook entry OR a prompt injection) so the
 *  model "remembers" the places. State persists across reloads.
 *
 *  Design constraints (see plan):
 *   - Live generator runs in a modal POPUP (iframes are stripped from
 *     chat messages by DOMPurify, but popup content is not sanitized).
 *   - We can't read state back out of the cross-origin iframe, so OUR
 *     UI owns the seed/params; JSON/PNG enter via manual file upload.
 * ================================================================== */

import {
    eventSource,
    event_types,
    setExtensionPrompt,
    extension_prompt_types,
    extension_prompt_roles,
    saveSettingsDebounced,
} from '../../../../script.js';
import { extension_settings, getContext } from '../../../extensions.js';
import { callGenericPopup, POPUP_TYPE, POPUP_RESULT } from '../../../popup.js';
import {
    loadWorldInfo,
    saveWorldInfo,
    createWorldInfoEntry,
    updateWorldInfoList,
    METADATA_KEY,
} from '../../../world-info.js';
import { SlashCommandParser } from '../../../slash-commands/SlashCommandParser.js';
import { SlashCommand } from '../../../slash-commands/SlashCommand.js';

import {
    GENERATORS,
    buildUrl,
    buildExportUrl,
    parseUrl,
    detectGenerator,
    defFor,
    jsonToText,
    randomSeed,
} from './generators.js';

const MODULE_NAME = 'MapGenerators';

const DEFAULT_SETTINGS = {
    enabled: true,
    language: 'en',
    defaultDepth: 4,        // injection depth for "inject" memory mode
    globalMaps: [],         // cross-chat library (copies of map objects)
    panels: { a: { open: false, mapId: null }, b: { open: false, mapId: null } }, // two docked viewers
    secondEnabled: false,   // is the second floating viewer (B) enabled
};

/* ------------------------------------------------------------------
 *  i18n
 * ------------------------------------------------------------------ */
const I18N = {
    en: {
        ext_title: 'Map Generators',
        enabled: 'Enable extension',
        language: 'Language',
        open_library: 'Open Map Library…',
        default_depth: 'Injection depth (inject mode)',
        attribution: 'Maps are generated by Watabou\'s tools (watabou.github.io). Generated maps are free to use; this extension only frames the public generators. Please credit Watabou.',
        reset_header: 'Reset',
        reset_button: 'Delete all extension data',
        reset_confirm: 'Delete ALL Map Generators data (global library + settings)?',
        lib_title: 'Map Library',
        lib_empty: 'No maps yet. Create one below.',
        lib_new: '+ New map',
        lib_chat_only: 'Open a chat to save maps to it.',
        col_open: 'Open',
        col_edit: 'Edit',
        col_delete: 'Delete',
        pick_generator: 'Choose a generator',
        gen_seed: 'Seed',
        gen_random: 'Randomize',
        gen_size: 'Size',
        gen_tags: 'Tags (comma-separated)',
        gen_save: 'Save this map',
        gen_paste: '…or paste a map URL from the generator',
        gen_open_new: 'Open in new tab',
        editor_title: 'Map',
        f_title: 'Title',
        f_generator: 'Generator',
        f_url: 'Map URL',
        f_reopen: 'Open generator',
        f_description: 'Description (what the AI reads)',
        desc_import_json: 'Import JSON → description',
        desc_vision: 'Describe via AI vision (PNG)',
        desc_thumb: 'Set PNG preview',
        desc_insert_chat: 'Insert preview into last message',
        mem_header: 'AI memory',
        mem_none: 'Off',
        mem_lorebook: 'Chat lorebook',
        mem_inject: 'Prompt injection',
        mem_depth: 'Depth',
        save: 'Save',
        delete: 'Delete',
        saved: 'Map saved',
        deleted: 'Map deleted',
        need_title: 'Please enter a title',
        json_ok: 'Description built from JSON',
        json_bad: 'Could not parse that JSON file',
        vision_run: 'Asking the model to describe the map…',
        vision_bad: 'Vision captioning failed (need a multimodal model configured)',
        vision_no: 'No connected multimodal model for captioning',
        applied_lore: 'Map written to chat lorebook',
        applied_inject: 'Map injected into the prompt',
        memory_off: 'AI memory turned off for this map',
        wand_label: 'Maps',
        panel_close: 'Close panel',
        panel_empty: 'No maps in this chat yet. Use ＋ to add one.',
        insert_link: 'Insert link into chat',
        link_inserted: 'Link added to the message box',
        open_export: 'Open export (download PNG/JSON to import)',
        export_opened: 'Export opened in a new tab',
        itch_note: 'This itch.io tool opens in a new tab (no embedding / no seed). Generate there, then export a PNG and set it as the preview.',
        no_seed: 'This generator has no seed to reroll',
        no_lorebook_msg: 'This chat has no lorebook. Create one automatically named «{name}» and bind it to the chat?',
        no_lorebook_create: 'Create lorebook',
        lorebook_created: 'Lorebook «{name}» created and bound to the chat',
        cancel: 'Cancel',
        reset_done: 'Extension data reset (settings + this chat\'s maps)',
        desc_import_md: 'Import Markdown → description',
        md_ok: 'Description loaded from Markdown',
        vision_ok: 'Description generated from the image',
        enable_second: 'Second floating viewer',
        wand_label2: 'Maps (2)',
        panel_max: 'Maximize / restore',
    },
    ru: {
        ext_title: 'Генераторы карт',
        enabled: 'Включить расширение',
        language: 'Язык',
        open_library: 'Открыть библиотеку карт…',
        default_depth: 'Глубина инжекта (режим inject)',
        attribution: 'Карты создаются инструментами Watabou (watabou.github.io). Готовые карты свободны в использовании; расширение лишь встраивает публичные генераторы. Указывайте авторство Watabou.',
        reset_header: 'Сброс',
        reset_button: 'Удалить все данные расширения',
        reset_confirm: 'Удалить ВСЕ данные Генераторов карт (глобальная библиотека + настройки)?',
        lib_title: 'Библиотека карт',
        lib_empty: 'Пока нет карт. Создайте новую ниже.',
        lib_new: '+ Новая карта',
        lib_chat_only: 'Откройте чат, чтобы сохранять карты в него.',
        col_open: 'Открыть',
        col_edit: 'Правка',
        col_delete: 'Удалить',
        pick_generator: 'Выберите генератор',
        gen_seed: 'Сид',
        gen_random: 'Случайно',
        gen_size: 'Размер',
        gen_tags: 'Теги (через запятую)',
        gen_save: 'Сохранить эту карту',
        gen_paste: '…или вставьте URL карты из генератора',
        gen_open_new: 'Открыть в новой вкладке',
        editor_title: 'Карта',
        f_title: 'Название',
        f_generator: 'Генератор',
        f_url: 'URL карты',
        f_reopen: 'Открыть генератор',
        f_description: 'Описание (его читает ИИ)',
        desc_import_json: 'Импорт JSON → описание',
        desc_vision: 'Описать через ИИ-vision (PNG)',
        desc_thumb: 'Задать превью PNG',
        desc_insert_chat: 'Вставить превью в последнее сообщение',
        mem_header: 'Память ИИ',
        mem_none: 'Выкл',
        mem_lorebook: 'Лорбук чата',
        mem_inject: 'Инжект в промпт',
        mem_depth: 'Глубина',
        save: 'Сохранить',
        delete: 'Удалить',
        saved: 'Карта сохранена',
        deleted: 'Карта удалена',
        need_title: 'Введите название',
        json_ok: 'Описание собрано из JSON',
        json_bad: 'Не удалось разобрать JSON-файл',
        vision_run: 'Просим модель описать карту…',
        vision_bad: 'ИИ-описание не удалось (нужна мультимодальная модель)',
        vision_no: 'Нет подключённой мультимодальной модели',
        applied_lore: 'Карта записана в лорбук чата',
        applied_inject: 'Карта добавлена в промпт',
        memory_off: 'Память ИИ для карты выключена',
        wand_label: 'Карты',
        panel_close: 'Закрыть панель',
        panel_empty: 'В этом чате ещё нет карт. Нажмите ＋, чтобы добавить.',
        insert_link: 'Вставить ссылку в чат',
        link_inserted: 'Ссылка добавлена в поле ввода',
        open_export: 'Открыть экспорт (скачать PNG/JSON для импорта)',
        export_opened: 'Экспорт открыт в новой вкладке',
        itch_note: 'Этот itch.io-инструмент открывается в новой вкладке (без встраивания и без seed). Сгенерируйте там, экспортируйте PNG и задайте его как превью.',
        no_seed: 'У этого генератора нет seed для пересоздания',
        no_lorebook_msg: 'У этого чата нет лорбука. Создать автоматически с именем «{name}» и привязать к чату?',
        no_lorebook_create: 'Создать лорбук',
        lorebook_created: 'Лорбук «{name}» создан и привязан к чату',
        cancel: 'Отмена',
        reset_done: 'Данные расширения сброшены (настройки + карты этого чата)',
        desc_import_md: 'Импорт Markdown → описание',
        md_ok: 'Описание загружено из Markdown',
        vision_ok: 'Описание сгенерировано по изображению',
        enable_second: 'Второе плавающее окно',
        wand_label2: 'Карты (2)',
        panel_max: 'Развернуть / свернуть',
    },
};

function t(key) {
    const lang = (extension_settings[MODULE_NAME] || {}).language || 'en';
    return (I18N[lang] && I18N[lang][key]) || I18N.en[key] || key;
}

function applyTranslations(root = document) {
    root.querySelectorAll('[data-mg-i18n]').forEach((el) => {
        const raw = el.getAttribute('data-mg-i18n');
        const m = raw.match(/^\[(.+?)\](.+)$/);
        if (m) el.setAttribute(m[1], t(m[2]));
        else el.textContent = t(raw);
    });
}

/* ------------------------------------------------------------------
 *  Settings bootstrap (forward-compatible migration)
 * ------------------------------------------------------------------ */
function getSettings() {
    if (!extension_settings[MODULE_NAME]) {
        extension_settings[MODULE_NAME] = structuredClone(DEFAULT_SETTINGS);
        return extension_settings[MODULE_NAME];
    }
    const s = extension_settings[MODULE_NAME];
    // Migrate the pre-v2 single panel state into panels.a.
    if (s.panel && !s.panels) {
        s.panels = { a: { open: !!s.panel.open, mapId: s.panel.mapId ?? null }, b: { open: false, mapId: null } };
        delete s.panel;
    }
    for (const [k, v] of Object.entries(DEFAULT_SETTINGS)) {
        if (s[k] === undefined) s[k] = structuredClone(v);
    }
    return s;
}

function toast(msg, type = 'info') {
    try { window.toastr?.[type]?.(msg); } catch { /* noop */ }
}

/* ------------------------------------------------------------------
 *  Per-chat map library  (lives in chat_metadata → survives reloads)
 * ------------------------------------------------------------------ */
function chatStore() {
    const ctx = getContext();
    if (!ctx || !ctx.chatMetadata) return null;
    if (!ctx.chatMetadata[MODULE_NAME]) ctx.chatMetadata[MODULE_NAME] = { maps: [] };
    if (!Array.isArray(ctx.chatMetadata[MODULE_NAME].maps)) ctx.chatMetadata[MODULE_NAME].maps = [];
    return ctx.chatMetadata[MODULE_NAME];
}

function getChatMaps() {
    return chatStore()?.maps ?? [];
}

function persistChat() {
    getContext()?.saveMetadataDebounced?.();
}

function newId() {
    return 'm' + randomSeed().toString(36) + Date.now().toString(36);
}

function lorebookNameForChat() {
    const ctx = getContext();
    const id = (ctx?.chatId || 'global').toString().replace(/[^\w-]+/g, '_');
    return `Maps_${id}`;
}

function injectKey(map) {
    return `MapGen_${map.id}`;
}

/** Text actually fed to the AI for a map. */
function formatForAi(map) {
    const desc = (map.description || '').trim() || `(${GENERATORS[map.generator]?.label || map.generator} map, no description)`;
    return desc;
}

/* ------------------------------------------------------------------
 *  AI memory:  lorebook entry  and/or  prompt injection
 * ------------------------------------------------------------------ */
const activeInjectKeys = new Set();

/** Suggested lorebook name: "<Character> - <chat>". */
function suggestedLorebookName() {
    const ctx = getContext();
    const char = ctx?.name2 || ctx?.characters?.[ctx?.characterId]?.name || 'Char';
    const chat = ctx?.chatId || 'chat';
    return `${char} - ${chat}`;
}

/**
 * Ensure the current chat has a bound lorebook. If a map already points
 * at one, reuse it. If the chat has one bound, reuse it. Otherwise warn
 * the user and offer to auto-create "<Character> - <chat>".
 * @returns {Promise<string|null>} bound lorebook name, or null if declined.
 */
async function ensureChatLorebook(map) {
    const ctx = getContext();
    if (map?.memory?.lorebook) return map.memory.lorebook;
    const bound = ctx?.chatMetadata?.[METADATA_KEY];
    if (bound) return bound;

    const suggested = suggestedLorebookName();
    const ok = await callGenericPopup(
        t('no_lorebook_msg').replace('{name}', suggested),
        POPUP_TYPE.CONFIRM, '',
        { okButton: t('no_lorebook_create'), cancelButton: t('cancel') },
    );
    if (ok !== POPUP_RESULT.AFFIRMATIVE) return null;

    // Create an empty lorebook and bind it to the chat.
    await saveWorldInfo(suggested, { entries: {} }, true);
    await updateWorldInfoList();
    if (ctx?.chatMetadata) {
        ctx.chatMetadata[METADATA_KEY] = suggested;
        persistChat();
    }
    toast(t('lorebook_created').replace('{name}', suggested), 'success');
    return suggested;
}

/** @returns {Promise<boolean>} whether the entry was written. */
async function applyLorebook(map) {
    const name = await ensureChatLorebook(map);
    if (!name) return false;   // user declined to create a lorebook

    let data;
    try { data = await loadWorldInfo(name); } catch { data = null; }
    if (!data || typeof data !== 'object' || !data.entries) data = { entries: {} };

    let entry = (map.memory.entryUid != null) ? data.entries[map.memory.entryUid] : null;
    if (!entry) {
        entry = createWorldInfoEntry(name, data);
        if (!entry) { toast(t('vision_bad'), 'error'); return false; }
        map.memory.entryUid = entry.uid;
    }
    entry.key = [map.title].filter(Boolean);
    entry.comment = `[Map] ${map.title}`;
    entry.content = formatForAi(map);
    entry.constant = false;   // keyword-triggered on the place name
    entry.disable = false;

    await saveWorldInfo(name, data, true);
    await updateWorldInfoList();
    map.memory.lorebook = name;
    return true;
}

async function disableLorebookEntry(map) {
    if (!map.memory.lorebook || map.memory.entryUid == null) return;
    let data;
    try { data = await loadWorldInfo(map.memory.lorebook); } catch { return; }
    if (data?.entries?.[map.memory.entryUid]) {
        data.entries[map.memory.entryUid].disable = true;
        await saveWorldInfo(map.memory.lorebook, data, true);
    }
}

function applyInject(map) {
    const depth = Number(map.memory.depth ?? getSettings().defaultDepth ?? 4);
    const key = injectKey(map);
    setExtensionPrompt(
        key,
        `[Map: ${map.title}] ${formatForAi(map)}`,
        extension_prompt_types.IN_CHAT,
        depth,
        false,
        extension_prompt_roles.SYSTEM,
    );
    activeInjectKeys.add(key);
}

function clearInject(map) {
    const key = injectKey(map);
    setExtensionPrompt(key, '', extension_prompt_types.IN_CHAT, 0);
    activeInjectKeys.delete(key);
}

/** Apply a map's chosen memory mode, clearing the other mode. */
async function applyMemory(map) {
    if (!getSettings().enabled) return;
    const mode = map.memory?.mode || 'none';
    if (mode === 'lorebook') {
        clearInject(map);
        const ok = await applyLorebook(map);
        if (!ok) { map.memory.mode = 'none'; persistChat(); return; }  // declined lorebook creation
        toast(t('applied_lore'), 'success');
    } else if (mode === 'inject') {
        await disableLorebookEntry(map);
        applyInject(map);
        toast(t('applied_inject'), 'success');
    } else {
        clearInject(map);
        await disableLorebookEntry(map);
        toast(t('memory_off'));
    }
}

/** On chat switch: clear all injects, then re-apply this chat's inject maps. */
function reinjectForCurrentChat() {
    for (const key of [...activeInjectKeys]) {
        setExtensionPrompt(key, '', extension_prompt_types.IN_CHAT, 0);
    }
    activeInjectKeys.clear();
    if (!getSettings().enabled) return;
    for (const map of getChatMaps()) {
        if (map.memory?.mode === 'inject') applyInject(map);
    }
}

/* ------------------------------------------------------------------
 *  File helpers (JSON parse, PNG → base64, vision captioning)
 * ------------------------------------------------------------------ */
function readFileText(file) {
    return new Promise((resolve, reject) => {
        const r = new FileReader();
        r.onload = () => resolve(String(r.result));
        r.onerror = reject;
        r.readAsText(file);
    });
}

function readFileDataUrl(file) {
    return new Promise((resolve, reject) => {
        const r = new FileReader();
        r.onload = () => resolve(String(r.result));
        r.onerror = reject;
        r.readAsDataURL(file);
    });
}

function stripDataUrl(dataUrl) {
    const i = dataUrl.indexOf('base64,');
    return i >= 0 ? dataUrl.slice(i + 'base64,'.length) : dataUrl;
}

async function describeViaVision(dataUrl) {
    // Lazy import: shared.js pulls in caption settings; only load on demand.
    let getMultimodalCaption;
    try {
        // shared.js lives in scripts/extensions/ — two levels up from this
        // third-party extension dir.
        ({ getMultimodalCaption } = await import('../../shared.js'));
    } catch {
        toast(t('vision_no'), 'warning');
        return null;
    }
    const prompt = (getSettings().language === 'ru')
        ? 'Опиши эту фэнтезийную карту для мастера игры: тип места (город/деревня/подземелье/регион), районы и ключевые объекты, стены/ворота/река/побережье, общая атмосфера. 3–5 предложений.'
        : 'Describe this fantasy map for a game master: kind of place (city/village/dungeon/region), districts and key features, walls/gates/river/coast, overall mood. 3–5 sentences.';
    try {
        const caption = await getMultimodalCaption(stripDataUrl(dataUrl), prompt);
        return (caption || '').trim() || null;
    } catch (e) {
        console.error('[MapGenerators] vision caption failed', e);
        toast(t('vision_bad'), 'error');
        return null;
    }
}

/** Attach a base64 PNG preview to the most recent chat message. */
function insertPreviewIntoChat(dataUrl) {
    const ctx = getContext();
    if (!ctx?.chat?.length) return;
    const idx = ctx.chat.length - 1;
    const msg = ctx.chat[idx];
    msg.extra = msg.extra || {};
    if (!Array.isArray(msg.extra.media)) msg.extra.media = [];
    msg.extra.media.push({ url: dataUrl, type: 'image' });
    // appendMediaToMessage uses jQuery methods (.find/.attr) on the element,
    // so pass a jQuery object — a raw DOM node throws and nothing renders.
    const $block = $(`#chat .mes[mesid="${idx}"]`);
    if ($block.length) ctx.appendMediaToMessage(msg, $block);
    ctx.saveChat?.();
}

/* ------------------------------------------------------------------
 *  UI — generator popup (the live iframe)
 * ------------------------------------------------------------------ */
async function openGeneratorPopup(generatorKey, existingMap = null) {
    const def = GENERATORS[generatorKey];
    if (!def) return;

    // itch.io tools: no URL/seed state and framing is unreliable, so we
    // present a launch card instead of an embedded (likely-blocked) iframe.
    if (def.embed === 'itch') {
        const $w = $('<div class="mg-itchcard"></div>');
        $w.append($(`<p>${t('itch_note')}</p>`));
        $w.append($(`<a class="menu_button" target="_blank" rel="noopener" href="${def.base}">${t('gen_open_new')}</a>`));
        const r = await callGenericPopup($w, POPUP_TYPE.CONFIRM, '', {
            wide: true, okButton: t('gen_save'), cancelButton: 'Close',
        });
        if (r !== POPUP_RESULT.AFFIRMATIVE) return null;
        if (existingMap) { existingMap.url = def.base; return existingMap; }
        return {
            id: newId(), generator: generatorKey, title: def.label,
            url: def.base, seed: null, params: {},
            thumbnail: null, description: '', descSource: 'manual',
            memory: { mode: 'none', lorebook: null, entryUid: null, depth: getSettings().defaultDepth },
        };
    }

    let seed = existingMap?.seed ?? randomSeed();
    const params = structuredClone(existingMap?.params ?? {});

    const $wrap = $('<div class="mg-genpopup"></div>');
    const $bar = $('<div class="mg-bar"></div>');

    const $seed = $(`<input type="text" class="text_pole mg-seed" />`).val(String(seed));
    const $rand = $(`<button class="menu_button" title="${t('gen_random')}">🎲</button>`);
    $bar.append($(`<span>${t('gen_seed')}</span>`), $seed, $rand);

    let $size, $tags;
    if (def.params.includes('size')) {
        $size = $(`<input type="number" class="text_pole mg-size" min="6" max="60" style="width:5em" />`).val(params.size ?? 15);
        $bar.append($(`<span>${t('gen_size')}</span>`), $size);
    }
    if (def.params.includes('tags')) {
        const ph = def.tagHint || t('gen_tags');
        $tags = $(`<input type="text" class="text_pole mg-tags" title="${t('gen_tags')}" placeholder="${ph}" />`).val((params.tags || []).join?.(',') ?? params.tags ?? '');
        $bar.append($tags);
    }

    const $frame = $(`<iframe class="mg-frame" referrerpolicy="no-referrer"></iframe>`);
    const $paste = $(`<input type="text" class="text_pole mg-paste" placeholder="${t('gen_paste')}" />`);
    const $newtab = $(`<a class="menu_button" target="_blank" rel="noopener">${t('gen_open_new')}</a>`);

    function currentParams() {
        const p = {};
        if ($size) p.size = Number($size.val()) || undefined;
        if ($tags) {
            const tg = String($tags.val()).split(',').map(s => s.trim()).filter(Boolean);
            if (tg.length) p.tags = tg;
        }
        return p;
    }
    function refresh() {
        const url = buildUrl(generatorKey, seed, currentParams());
        $frame.attr('src', url);
        $newtab.attr('href', url);
    }
    $rand.on('click', () => { seed = randomSeed(); $seed.val(String(seed)); refresh(); });
    $seed.on('change', () => { seed = $seed.val().trim() || seed; refresh(); });
    $size?.on('change', refresh);
    $tags?.on('change', refresh);
    $paste.on('change', () => {
        const parsed = parseUrl($paste.val().trim());
        if (parsed.seed) { seed = parsed.seed; $seed.val(String(seed)); }
        if (parsed.params.size && $size) $size.val(parsed.params.size);
        if (parsed.params.tags && $tags) $tags.val(parsed.params.tags);
        refresh();
    });

    $wrap.append($bar, $frame, $('<div class="mg-row"></div>').append($paste, $newtab));
    refresh();

    const result = await callGenericPopup($wrap, POPUP_TYPE.CONFIRM, '', {
        wide: true, large: true, wider: true, allowVerticalScrolling: true,
        okButton: t('gen_save'), cancelButton: 'Close',
    });
    if (result !== POPUP_RESULT.AFFIRMATIVE) return null;

    // Build / update the map object from the state WE own.
    const url = buildUrl(generatorKey, seed, currentParams());
    if (existingMap) {
        existingMap.seed = seed;
        existingMap.params = currentParams();
        existingMap.url = url;
        return existingMap;
    }
    return {
        id: newId(),
        generator: generatorKey,
        title: `${def.label} ${seed}`,
        url, seed, params: currentParams(),
        thumbnail: null,
        description: '',
        descSource: 'manual',
        memory: { mode: 'none', lorebook: null, entryUid: null, depth: getSettings().defaultDepth },
    };
}

/* ------------------------------------------------------------------
 *  UI — map editor popup
 * ------------------------------------------------------------------ */
async function openMapEditor(map, { isNew = false } = {}) {
    const def = GENERATORS[map.generator];

    const $f = $('<div class="mg-editor"></div>');
    const row = (label, ctrl) => $('<div class="mg-field"></div>').append($(`<label>${label}</label>`), ctrl);

    const $title = $(`<input type="text" class="text_pole" />`).val(map.title);
    const $url = $(`<input type="text" class="text_pole" readonly />`).val(map.url);
    const $reopen = $(`<button class="menu_button">${t('f_reopen')}</button>`);
    const $desc = $(`<textarea class="text_pole mg-desc" rows="5"></textarea>`).val(map.description);

    const $jsonBtn = $(`<button class="menu_button">${t('desc_import_json')}</button>`);
    const $jsonInput = $(`<input type="file" accept=".json,application/json" hidden />`);
    const $mdBtn = $(`<button class="menu_button">${t('desc_import_md')}</button>`);
    const $mdInput = $(`<input type="file" accept=".md,.markdown,.txt,text/markdown,text/plain" hidden />`);
    const $visionBtn = $(`<button class="menu_button">${t('desc_vision')}</button>`);
    const $thumbBtn = $(`<button class="menu_button">${t('desc_thumb')}</button>`);
    const $pngInput = $(`<input type="file" accept="image/*" hidden />`);
    const $insertBtn = $(`<button class="menu_button">${t('desc_insert_chat')}</button>`);
    let pendingPng = map.thumbnail;
    let pngForVision = null;

    // memory controls
    const mkRadio = (val, lbl) => $(`<label class="mg-radio"><input type="radio" name="mg-mem" value="${val}"> ${lbl}</label>`);
    const $memNone = mkRadio('none', t('mem_none'));
    const $memLore = mkRadio('lorebook', t('mem_lorebook'));
    const $memInj = mkRadio('inject', t('mem_inject'));
    const $depth = $(`<input type="number" class="text_pole" min="0" max="100" style="width:5em" />`).val(map.memory?.depth ?? getSettings().defaultDepth);
    [$memNone, $memLore, $memInj].forEach($r => {
        if ($r.find('input').val() === (map.memory?.mode || 'none')) $r.find('input').prop('checked', true);
    });

    $reopen.on('click', async () => {
        const updated = await openGeneratorPopup(map.generator, map);
        if (updated) $url.val(updated.url);
    });
    $jsonBtn.on('click', () => $jsonInput.trigger('click'));
    $jsonInput.on('change', async (e) => {
        const file = e.target.files?.[0]; if (!file) return;
        try {
            const data = JSON.parse(await readFileText(file));
            // Dedicated parser if the generator has one, else generic (full, no truncation).
            $desc.val(def?.parse ? def.parse(data) : jsonToText(data));
            map.descSource = 'json';
            toast(t('json_ok'), 'success');
        } catch { toast(t('json_bad'), 'error'); }
    });
    $mdBtn.on('click', () => $mdInput.trigger('click'));
    $mdInput.on('change', async (e) => {
        const file = e.target.files?.[0]; if (!file) return;
        const text = (await readFileText(file)).trim();
        if (text) { $desc.val(text); map.descSource = 'markdown'; toast(t('md_ok'), 'success'); }
    });
    $thumbBtn.on('click', () => $pngInput.trigger('click'));
    $pngInput.on('change', async (e) => {
        const file = e.target.files?.[0]; if (!file) return;
        pendingPng = await readFileDataUrl(file);
        pngForVision = pendingPng;
        $thumbBtn.text('✓ ' + t('desc_thumb'));
    });
    $visionBtn.on('click', async () => {
        const src = pngForVision || pendingPng;
        if (!src) { toast(t('desc_thumb'), 'warning'); return; }
        toast(t('vision_run'));
        const caption = await describeViaVision(src);
        if (caption) { $desc.val(caption); map.descSource = 'vision'; toast(t('vision_ok'), 'success'); }
    });
    $insertBtn.on('click', () => {
        if (pendingPng) insertPreviewIntoChat(pendingPng);
    });

    $f.append(
        row(t('f_title'), $title),
        row(t('f_generator'), $(`<span class="mg-static">${def?.label || map.generator}</span>`)),
        row(t('f_url'), $('<div class="mg-row"></div>').append($url, $reopen)),
        row(t('f_description'), $desc),
        $('<div class="mg-row mg-wrap"></div>').append($jsonBtn, $mdBtn, $visionBtn, $thumbBtn, $insertBtn, $jsonInput, $mdInput, $pngInput),
        $(`<h4>${t('mem_header')}</h4>`),
        $('<div class="mg-row mg-wrap"></div>').append($memNone, $memLore, $memInj,
            $('<span class="mg-depthwrap"></span>').append($(`<span>${t('mem_depth')}</span>`), $depth)),
    );

    const result = await callGenericPopup($f, POPUP_TYPE.CONFIRM, '', {
        wide: true, allowVerticalScrolling: true, okButton: t('save'), cancelButton: 'Cancel',
    });
    if (result !== POPUP_RESULT.AFFIRMATIVE) return false;

    const title = $title.val().trim();
    if (!title) { toast(t('need_title'), 'warning'); return false; }

    map.title = title;
    map.description = $desc.val();
    map.thumbnail = pendingPng;
    map.memory = map.memory || {};
    map.memory.mode = $f.find('input[name="mg-mem"]:checked').val() || 'none';
    map.memory.depth = Number($depth.val()) || getSettings().defaultDepth;

    // Save into the chat library.
    const store = chatStore();
    if (store) {
        if (isNew) store.maps.push(map);
        persistChat();
    }
    await applyMemory(map);
    toast(t('saved'), 'success');
    return true;
}

/* ------------------------------------------------------------------
 *  UI — library popup
 * ------------------------------------------------------------------ */
async function openLibrary() {
    const $lib = $('<div class="mg-library"></div>');

    function render() {
        $lib.empty();
        const ctx = getContext();
        if (!ctx?.chatMetadata) {
            $lib.append($(`<p class="mg-empty">${t('lib_chat_only')}</p>`));
        } else {
            const maps = getChatMaps();
            if (!maps.length) $lib.append($(`<p class="mg-empty">${t('lib_empty')}</p>`));
            for (const map of maps) {
                const def = GENERATORS[map.generator];
                const $card = $('<div class="mg-card"></div>');
                const memBadge = map.memory?.mode && map.memory.mode !== 'none'
                    ? `<span class="mg-badge">${map.memory.mode === 'lorebook' ? '📖' : '💉'}</span>` : '';
                $card.append($(`
                    <div class="mg-card-main">
                        ${map.thumbnail ? `<img class="mg-thumb" src="${map.thumbnail}">` : '<div class="mg-thumb mg-noimg">🗺️</div>'}
                        <div class="mg-card-text">
                            <div class="mg-card-title">${$('<i>').text(map.title).html()} ${memBadge}</div>
                            <div class="mg-card-sub">${def?.label || map.generator}</div>
                        </div>
                    </div>`));
                const $open = $(`<button class="menu_button" title="${t('col_open')}">↗</button>`);
                const $edit = $(`<button class="menu_button" title="${t('col_edit')}">✎</button>`);
                const $del = $(`<button class="menu_button" title="${t('col_delete')}">🗑</button>`);
                $open.on('click', () => window.open(map.url, '_blank', 'noopener'));
                $edit.on('click', async () => { if (await openMapEditor(map)) render(); });
                $del.on('click', async () => {
                    clearInject(map);
                    await disableLorebookEntry(map);
                    const maps2 = getChatMaps();
                    const i = maps2.indexOf(map);
                    if (i >= 0) maps2.splice(i, 1);
                    persistChat();
                    toast(t('deleted'));
                    render();
                });
                $card.append($('<div class="mg-card-actions"></div>').append($open, $edit, $del));
                $lib.append($card);
            }
        }

        // "New map" → generator picker
        const $new = $(`<button class="menu_button mg-new">${t('lib_new')}</button>`);
        $new.on('click', async () => {
            const pick = await pickGenerator();
            if (!pick) return;
            const map = await openGeneratorPopup(pick);
            if (map) { await openMapEditor(map, { isNew: true }); render(); }
        });
        $lib.append($new);
    }

    render();
    await callGenericPopup($lib, POPUP_TYPE.TEXT, '', {
        wide: true, large: true, allowVerticalScrolling: true, okButton: 'Close',
    });
}

async function pickGenerator() {
    const $grid = $('<div class="mg-pick"></div>');
    let chosen = null;
    for (const def of Object.values(GENERATORS)) {
        const $b = $(`<button class="menu_button mg-pick-btn">${def.label}</button>`);
        $b.on('click', () => { chosen = def.key; $b.closest('dialog')[0]?.querySelector('.popup-button-ok')?.click(); });
        $grid.append($b);
    }
    await callGenericPopup($grid, POPUP_TYPE.TEXT, '', { okButton: 'Close', wide: true });
    return chosen;
}

/* ------------------------------------------------------------------
 *  Chat insertion helpers (client-only)
 * ------------------------------------------------------------------ */
/** Insert a clickable map link into the chat input box. */
function insertMapLink(map) {
    if (!map) return;
    const ta = document.querySelector('#send_textarea');
    const md = `[🗺️ ${map.title}](${map.url})`;
    if (ta) {
        const v = ta.value || '';
        ta.value = v + (v && !v.endsWith(' ') ? ' ' : '') + md + ' ';
        ta.dispatchEvent(new Event('input', { bubbles: true }));
        ta.focus();
    }
    toast(t('link_inserted'), 'success');
}

/** Open the generator's export URL (downloads PNG/JSON the user re-imports). */
function openExport(map) {
    if (!map) return;
    const def = defFor(map);
    let url = map.url;
    if (def.embed === 'gh') url = buildExportUrl(map.generator, map.seed, map.params, def.json ? 'json' : 'png');
    window.open(url, '_blank', 'noopener');
    toast(t('export_opened'));
}

/* ------------------------------------------------------------------
 *  Docked floating viewers (map beside the chat). Two INDEPENDENT
 *  panels (A and B) share one factory; each floats over the character
 *  chat (not bound to any message) and is dragged via our own
 *  Pointer-Events handler (works on touch + mouse), with position
 *  persisted in settings.
 * ------------------------------------------------------------------ */
function panelState(key) {
    const s = getSettings();
    if (!s.panels) s.panels = { a: { open: false, mapId: null }, b: { open: false, mapId: null } };
    if (!s.panels[key]) s.panels[key] = { open: false, mapId: null };
    return s.panels[key];
}

/* --- geometry: our own Pointer-Events drag (ST's dragElement is mouse-only,
       so it does NOT work on touch screens). Position is persisted in
       settings so it survives reloads on every device. --- */
function saveRect(key, el) {
    const r = el.getBoundingClientRect();
    panelState(key).rect = { left: Math.round(r.left), top: Math.round(r.top), width: el.offsetWidth, height: el.offsetHeight };
    saveSettingsDebounced();
}
function applyRect(key, el) {
    const rect = panelState(key).rect;
    if (!rect) return;
    el.style.right = 'auto';
    el.style.left = `${rect.left || 0}px`;
    el.style.top = `${rect.top || 0}px`;
    if (rect.width) el.style.width = `${rect.width}px`;
    if (rect.height) el.style.height = `${rect.height}px`;
}
function applyMax(key, el) {
    el.classList.toggle('mg-maximized', !!panelState(key).maximized);
}
function toggleMax(key, el) {
    panelState(key).maximized = !panelState(key).maximized;
    saveSettingsDebounced();
    applyMax(key, el);
}
/** Make a panel draggable by its handle via Pointer Events (mouse + touch). */
function makeMovable(el, handle, key) {
    let sx = 0, sy = 0, sl = 0, st = 0, dragging = false;
    handle.style.touchAction = 'none';   // stop the page scrolling while dragging
    handle.addEventListener('pointerdown', (e) => {
        if (panelState(key).maximized) return;  // don't drag while maximized
        dragging = true;
        const r = el.getBoundingClientRect();
        sx = e.clientX; sy = e.clientY; sl = r.left; st = r.top;
        el.style.right = 'auto'; el.style.left = `${r.left}px`; el.style.top = `${r.top}px`;
        try { handle.setPointerCapture(e.pointerId); } catch { /* noop */ }
        e.preventDefault();
    });
    handle.addEventListener('pointermove', (e) => {
        if (!dragging) return;
        let nl = sl + (e.clientX - sx);
        let nt = st + (e.clientY - sy);
        nl = Math.max(0, Math.min(nl, window.innerWidth - 60));
        nt = Math.max(0, Math.min(nt, window.innerHeight - 30));
        el.style.left = `${nl}px`; el.style.top = `${nt}px`;
    });
    const end = (e) => {
        if (!dragging) return;
        dragging = false;
        try { handle.releasePointerCapture(e.pointerId); } catch { /* noop */ }
        saveRect(key, el);
    };
    handle.addEventListener('pointerup', end);
    handle.addEventListener('pointercancel', end);
}

function createPanel(cfg) {
    // cfg = { key:'a'|'b', id:'mapGenPanel'|'mapGenPanel2' }
    const sel = `#${cfg.id}`;
    let built = false;

    function activeMap() {
        const maps = getChatMaps();
        if (!maps.length) return null;
        const id = panelState(cfg.key).mapId;
        return maps.find(m => m.id === id) || maps[0];
    }

    function renderBody() {
        const $body = $(`${sel} .mg-panel-body`);
        if (!$body.length) return;
        $body.empty();
        const map = activeMap();
        if (!map) { $body.append($(`<p class="mg-empty">${t('panel_empty')}</p>`)); return; }
        const def = defFor(map);
        if (def.embed === 'itch') {
            $body.append($(`<div class="mg-itchcard"><p>${t('itch_note')}</p>
                <a class="menu_button" target="_blank" rel="noopener" href="${map.url}">${t('gen_open_new')}</a></div>`));
        } else {
            $body.append($(`<iframe class="mg-frame" referrerpolicy="no-referrer" src="${map.url}"></iframe>`));
        }
    }

    function refreshSelect() {
        const $s = $(`${sel} .mg-panel-select`);
        if (!$s.length) return;
        const maps = getChatMaps();
        const active = activeMap();
        $s.empty();
        if (!maps.length) { $s.append($(`<option>${t('panel_empty')}</option>`)); return; }
        for (const m of maps) {
            const o = $(`<option></option>`).val(m.id).text(m.title);
            if (active && m.id === active.id) o.prop('selected', true);
            $s.append(o);
        }
    }

    // Only render a panel that is actually open — avoids loading the
    // iframe of a hidden/closed/disabled viewer on every chat change.
    function render() {
        if (!built || !panelState(cfg.key).open) return;
        refreshSelect();
        renderBody();
    }

    function build() {
        if (built || !$('#movingDivs').length) return;
        const $panel = $(`
            <div id="${cfg.id}" class="drawer-content flexGap5 mg-panel" style="display:none">
                <div id="${cfg.id}header" class="fa-fw fa-solid fa-grip drag-grabber"></div>
                <div class="mg-panel-bar">
                    <select class="text_pole mg-panel-select"></select>
                    <button class="menu_button mg-panel-new" title="${t('lib_new')}">＋</button>
                    <button class="menu_button mg-panel-rand" title="${t('gen_random')}">🎲</button>
                    <button class="menu_button mg-panel-max" title="${t('panel_max')}">⛶</button>
                    <button class="menu_button mg-panel-close" title="${t('panel_close')}">✕</button>
                </div>
                <div class="mg-panel-body"></div>
                <div class="mg-panel-actions">
                    <button class="menu_button mg-panel-link" title="${t('insert_link')}">🔗</button>
                    <button class="menu_button mg-panel-export" title="${t('open_export')}">⬇</button>
                    <button class="menu_button mg-panel-edit" title="${t('col_edit')}">✎</button>
                    <button class="menu_button mg-panel-full" title="${t('open_library')}">⤢</button>
                </div>
            </div>`);
        $('#movingDivs').append($panel);
        const el = $panel[0];
        const grabber = $panel.find('.drag-grabber')[0];
        makeMovable(el, grabber, cfg.key);   // touch + mouse drag
        applyRect(cfg.key, el);
        applyMax(cfg.key, el);

        // Persist manual resizing (CSS `resize: both`) — but not while
        // maximized (that geometry must not overwrite the saved rect).
        try {
            new ResizeObserver(() => {
                if (panelState(cfg.key).open && !panelState(cfg.key).maximized) saveRect(cfg.key, el);
            }).observe(el);
        } catch { /* ResizeObserver unsupported — drag still persists size */ }

        $panel.find('.mg-panel-max').on('click', () => toggleMax(cfg.key, el));
        $panel.find('.mg-panel-select').on('change', function () {
            panelState(cfg.key).mapId = $(this).val(); saveSettingsDebounced();
            renderBody();
        });
        $panel.find('.mg-panel-new').on('click', async () => {
            const pick = await pickGenerator();
            if (!pick) return;
            const map = await openGeneratorPopup(pick);
            if (!map) return;
            // mirror the library flow: editor pushes the map on save → no orphan on cancel
            if (await openMapEditor(map, { isNew: true })) {
                panelState(cfg.key).mapId = map.id; saveSettingsDebounced();
                renderAllPanels();
            }
        });
        $panel.find('.mg-panel-rand').on('click', () => {
            const map = activeMap();
            if (!map) return;
            const def = defFor(map);
            if (def.embed !== 'gh' || !def.seedable) { toast(t('no_seed')); return; }
            map.seed = randomSeed();
            map.url = buildUrl(map.generator, map.seed, map.params);
            persistChat();
            renderBody();
        });
        $panel.find('.mg-panel-close').on('click', () => toggle(false));
        $panel.find('.mg-panel-link').on('click', () => insertMapLink(activeMap()));
        $panel.find('.mg-panel-export').on('click', () => openExport(activeMap()));
        $panel.find('.mg-panel-edit').on('click', async () => {
            const map = activeMap();
            if (map && await openMapEditor(map)) render();
        });
        $panel.find('.mg-panel-full').on('click', openLibrary);
        built = true;
    }

    function toggle(forceOpen) {
        build();
        if (!built) return;
        const st = panelState(cfg.key);
        const open = (forceOpen === undefined) ? !st.open : forceOpen;
        st.open = open;
        saveSettingsDebounced();
        $(sel).toggle(open);
        if (open) { applyRect(cfg.key, $(sel)[0]); applyMax(cfg.key, $(sel)[0]); render(); }
    }

    return { cfg, build, render, toggle, get built() { return built; } };
}

const PANELS = {
    a: createPanel({ key: 'a', id: 'mapGenPanel' }),
    b: createPanel({ key: 'b', id: 'mapGenPanel2' }),
};

function renderAllPanels() { for (const p of Object.values(PANELS)) p.render(); }
function buildAllPanels() { for (const p of Object.values(PANELS)) p.build(); }

/** Restore open panels after load (B only if the second viewer is enabled). */
function restorePanels() {
    if (panelState('a').open) PANELS.a.toggle(true);
    if (getSettings().secondEnabled && panelState('b').open) PANELS.b.toggle(true);
}

function addWandButton() {
    if (!$('#extensionsMenu').length) return;
    if (!$('#mapgen_wand_container').length) {
        const $a = $(`
            <div id="mapgen_wand_container" class="list-group-item flex-container flexGap5 interactable" tabindex="0">
                <div class="fa-fw fa-solid fa-map extensionsMenuExtensionButton"></div>
                <span>${t('wand_label')}</span>
            </div>`);
        $a.on('click', () => PANELS.a.toggle());
        $('#extensionsMenu').append($a);
    }
    // Second-viewer wand entry: present only while enabled in settings.
    const wantB = !!getSettings().secondEnabled;
    const $bExisting = $('#mapgen_wand_container2');
    if (wantB && !$bExisting.length) {
        const $b = $(`
            <div id="mapgen_wand_container2" class="list-group-item flex-container flexGap5 interactable" tabindex="0">
                <div class="fa-fw fa-solid fa-map-location-dot extensionsMenuExtensionButton"></div>
                <span>${t('wand_label2')}</span>
            </div>`);
        $b.on('click', () => PANELS.b.toggle());
        $('#extensionsMenu').append($b);
    } else if (!wantB && $bExisting.length) {
        $bExisting.remove();
    }
}

/* ------------------------------------------------------------------
 *  Settings drawer
 * ------------------------------------------------------------------ */
const SETTINGS_HTML = `
<div class="map-generators-settings">
    <div class="inline-drawer">
        <div class="inline-drawer-toggle inline-drawer-header">
            <b data-mg-i18n="ext_title">Map Generators</b>
            <div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div>
        </div>
        <div class="inline-drawer-content">
            <label class="checkbox_label">
                <input type="checkbox" id="mg_enabled" />
                <span data-mg-i18n="enabled">Enable extension</span>
            </label>
            <label for="mg_language" data-mg-i18n="language">Language</label>
            <select id="mg_language" class="text_pole">
                <option value="en">English</option>
                <option value="ru">Русский</option>
            </select>
            <label for="mg_depth" data-mg-i18n="default_depth">Injection depth</label>
            <input type="number" id="mg_depth" class="text_pole" min="0" max="100" />
            <label class="checkbox_label">
                <input type="checkbox" id="mg_second" />
                <span data-mg-i18n="enable_second">Second floating viewer</span>
            </label>
            <div class="mg-row" style="margin-top:8px">
                <input type="button" class="menu_button" id="mg_open_lib" data-mg-i18n="[value]open_library" value="Open Map Library…" />
            </div>
            <small class="mg-hint" data-mg-i18n="attribution"></small>
            <h4 data-mg-i18n="reset_header">Reset</h4>
            <input type="button" class="menu_button" id="mg_reset" data-mg-i18n="[value]reset_button" value="Delete all extension data" />
        </div>
    </div>
</div>`;

function wireSettings() {
    const s = getSettings();
    $('#mg_enabled').prop('checked', s.enabled).on('change', function () {
        s.enabled = $(this).prop('checked'); saveSettingsDebounced();
        reinjectForCurrentChat();
    });
    $('#mg_language').val(s.language).on('change', function () {
        s.language = $(this).val(); saveSettingsDebounced();
        applyTranslations(document.querySelector('.map-generators-settings'));
    });
    $('#mg_depth').val(s.defaultDepth).on('change', function () {
        s.defaultDepth = Number($(this).val()) || 4; saveSettingsDebounced();
    });
    $('#mg_second').prop('checked', s.secondEnabled).on('change', function () {
        s.secondEnabled = $(this).prop('checked'); saveSettingsDebounced();
        addWandButton();                       // add/remove the second wand entry
        if (s.secondEnabled) PANELS.b.toggle(true);   // show it right away
        else PANELS.b.toggle(false);                  // hide if disabled
    });
    $('#mg_open_lib').on('click', openLibrary);
    $('#mg_reset').off('click.mg').on('click.mg', async () => {
        const ok = await callGenericPopup(t('reset_confirm'), POPUP_TYPE.CONFIRM);
        if (ok !== POPUP_RESULT.AFFIRMATIVE) return;

        // 1) Drop all active prompt injections.
        for (const key of [...activeInjectKeys]) setExtensionPrompt(key, '', extension_prompt_types.IN_CHAT, 0);
        activeInjectKeys.clear();

        // 2) Clear the current chat's maps (disable their lorebook entries first).
        const store = chatStore();
        if (store) {
            for (const map of [...store.maps]) { try { await disableLorebookEntry(map); } catch { /* noop */ } }
            store.maps = [];
            persistChat();
        }

        // 3) Reset settings IN PLACE so existing change-handler closures stay valid.
        const cur = getSettings();
        for (const k of Object.keys(cur)) delete cur[k];
        Object.assign(cur, structuredClone(DEFAULT_SETTINGS));
        saveSettingsDebounced();

        // 4) Hide both docked panels, clear their dragged geometry, refresh UI.
        $('#mapGenPanel, #mapGenPanel2').each((_, el) => {
            el.classList.remove('mg-maximized');
            el.style.left = el.style.top = el.style.width = el.style.height = el.style.right = '';
        }).hide();
        $('#mapgen_wand_container2').remove();
        $('#mg_enabled').prop('checked', cur.enabled);
        $('#mg_language').val(cur.language);
        $('#mg_depth').val(cur.defaultDepth);
        $('#mg_second').prop('checked', cur.secondEnabled);
        applyTranslations(document.querySelector('.map-generators-settings'));
        renderAllPanels();

        toast(t('reset_done'), 'success');
    });
}

/* ------------------------------------------------------------------
 *  Bootstrap
 * ------------------------------------------------------------------ */
jQuery(async () => {
    try {
        getSettings();

        const $host = $('#extensions_settings2').length
            ? $('#extensions_settings2')
            : ($('#extensions_settings').length ? $('#extensions_settings') : $('body'));
        $host.append(SETTINGS_HTML);
        applyTranslations(document.querySelector('.map-generators-settings'));
        wireSettings();

        // /map slash command opens the library.
        try {
            SlashCommandParser.addCommandObject(SlashCommand.fromProps({
                name: 'map',
                helpString: 'Open the Map Generators library',
                callback: () => { openLibrary(); return ''; },
            }));
        } catch (e) { console.warn('[MapGenerators] slash command registration failed', e); }

        // Docked floating viewers + wand-menu button(s) near the chat.
        addWandButton();
        buildAllPanels();

        const onChatChanged = () => { reinjectForCurrentChat(); renderAllPanels(); };

        // Re-apply prompt injections + refresh the viewers when the chat changes.
        if (event_types?.CHAT_CHANGED) {
            eventSource.on(event_types.CHAT_CHANGED, onChatChanged);
        }
        if (event_types?.APP_READY) {
            eventSource.on(event_types.APP_READY, () => {
                reinjectForCurrentChat();
                addWandButton();
                restorePanels();          // restore docked viewers
            });
        }
        // If APP_READY already fired, restore the viewers now.
        restorePanels();

        console.log('[MapGenerators] loaded');
    } catch (e) {
        console.error('[MapGenerators] init failed', e);
    }
});
